import Head from "next/head"
import A_list from "./A_list"
import Article from "./Article"
import { GetStaticProps } from "next"
// import mysql from 'mysql2'
import mysql from 'mysql2/promise'

type ArticleProps = React.ComponentProps<typeof Article>
type A_listProps = {
    articles:ArticleProps[]
}

let db = {
    host:'localhost',
    user:'user',
    password:'web',
    database:'web'
}

export default function Home({articles}:A_listProps){
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>

            </header>
            <main>
                <A_list articles={articles}/>
            </main>
            <footer>

            </footer>
        </>
    )
}

export const getStaticProps:GetStaticProps<{articles:ArticleProps[]}> = async (context) => {
    console.log('getstaticprops');
    console.log(context);
    let articles:ArticleProps[] = []
    let connection = await mysql.createConnection(db)
    try {
        let [rows,fields] = await connection.query('select src,alt,title,descript from web')
            if(rows instanceof Array)
                rows.forEach(element => {
                    console.log(element);
                    articles.push(element as ArticleProps)
                });
    } catch (error) {
        console.log(error);
    } finally {
        connection.end()
    }
    console.log('Articles', articles);
    return {
        props:{
            articles,
        },
    }
}